- README.md
Simple suggestions about actions they can do to help more.
> added suggestions section to README.md

- README.md
I think "Persepolis" is one of the most important open-source projects and it's better to be on the list.
I hope this could help to get things better with GitHub :(
> Add "Persepolis" to the projects list

- README.md
- together/rajabiseraji/index.js
> Update together and README

- README.md
- together/jeromegamez/together.php
Related: https://dev.to/jeromegamez/i-am-lucky-you-are-not-2eco
Love from Germany!
> Add jeromegamez

- README.md
- together/jocs/index.html
> support from China

- README.md
I also added a link in my most popular [repository](https://github.com/Separius/awesome-sentence-embedding#github-please-do-not-ban-me) :))
> add my support

- README.md
- together/alimpfard/main.ctr
Must. Protect. Foss.
~ alimpfard
> More support~

- README.md
I added my name as a supporter.
> Add my name as a supporter

- README.md
- together/sadrahallaj/Main.java
- together/sadrahallaj/index.js
Github is for everyone - sadrahallaj
>  Github is for everyone - sadrahallaj

- together/mohmehdi/Program.cs
> file added

- README.md
I added my name to supporters section.
> Add my name to supporters

- README.md
- together/molaeiali/main.rb
> Support from Iran

- together/meshkati/main.lua
> Meshkati from Iran

- README.md
I support you, GitHub is not a good place for the political games
> Supporters are growing

- together/mahmoud-eskandari/free_software_free_world.lua
Mahmoud Eskandari from Iran 🇮🇷
> Mahmoud Eskandari from Iran 🇮🇷

- README.md
yet another supporter for supporters list.
> Add kave mohammadi to supporters

- README.md
- together/gionuno/dontbanus.cpp
> #DontBanUs

- README.md
- together/saeedmhq/main.py
> Python code + Supporters

- README.md
> Add ShutHub to ReadMe

- together/AliHaydari/Program.cs
Ali Haydari from Iran **IR** ([AliHaydari](https://github.com/AliHaydari))
> Github for Everyone

- together/Support-from-China
Github是全人类的共同财富、搞壁垒主义只会引起全世界人民的抗议
> Github是全人类的共同财富

- togheter/main.py
I wrongly merge toghether file
> Revert "Create main.py"

- together/MohammadSalek/github_for_all.py
> free github

- README.md
- Abdus from India 🇮🇳 ([thisisabdus](https://github.com/thisosabdus) was added twice!.
- You can also added my name in supporting the project.
> Removed Duplicate Account.

- together/pooryadb
> from poorya db for freedom

- together/sbabaei/Program.cs
> saeid babaei

- README.md
> add zbyte64 to supporters

- README.md
> Fix my mistake

- README-CN.md
- README-ES.md
- README-IT.md
- README.md
- together/MatteoPieroni/index.js
I hope this helps a little bit!
> Added my name. Translated the readme in italian

- README.md
- together/angusmglfraser/GithubIsForEveryone.java
> Github is for everyone

- together/zbyte64/main.py
Wrote a more personalized statement on the matter.
> add statement by Jason kraus

- together/tleen/index.md
You are not alone. Keep trying.
> Sign by tleen

- together/EliasAHH/together.js
Hope this all gets resolved. You have my support!
>  Hoping for the best

- README-FR.MD
Here is my french translation of the README
> French translation

- README.md
Added my name, nationality and GitHub profile address to show support and solidarity with this project.
> Add myself to supporters' list

- together/rbagd/main.R
Stop pushing politics into code
> Join the movement

- README-FR.MD
I've corrected some spelling mistakes in the french version of the open letter :)
> Fix some spelling mistake in the french version

- README-FR.MD
I've forgot some spelling mistakes in my last [PR](https://github.com/1995parham/github-do-not-ban-us/pull/508)
> Fix some spelling mistakes in the french version 2/2

- README.md
- together/arctair/index.js
- together/arctair/main.groovy
- together/arctair/script.py
- together/arctair/script.sh
> add arctair

- README.md
- together/ahmadsalimi/GithubForEveryone.java
> ahmad salimi

- together/naltun/github-is-for-everyone.sh
> GitHub is for everyone (Armenian)

- README-IT.md
- README.md
- together/MarcoBuster/broadcast.py
I would like to show my support for this campaign!
> Fix typos in README-it.md + Telegram bot

- README.md
- together/aliraza7926/c++.cpp
- together/aliraza7926/python.py
> add my name into supporters list and careate aliraza7926 file 

- README.md
GitHub is for everyone! Support from china!
> GitHub is for everyone! Support from China!

- README.md
- together/barce/github_is_for_everyone.cc
> Adding barce

- together/rohzek/Program.cs
> Rohzek supporting from the U.S.

- together/MiladGanjAli/index.php
> Milad GanjAli

- README.md
- together/elanlb/main.cpp
Supporting the cause according to the readme document!
> My Support

- together/realpg/support.asm
> Supported from China!

- together/rrkane/preserveOpenSource.js
> Preserve open source

- together/marsvet/main.c
> Support from marsvet

- together/maacpiash/DoNotBan.csproj
- together/maacpiash/Program.cs
If you have .NET Core SDK installed, you
can run this program by `dotnet run`
command.
> Add a C# program

- README-CN.md
I reorganized the language to help Chinese users better understand. It is more vivid and no longer like machine translation.
Some parts of my translation are not in place, others are welcome to continue to optimize.
> Make README-CN.md more vivid

- together/arminkz/ruby.rb
i didn’t add my name to supporters i assume you that yourself. thanks. #githubForEveryone
> Armin from Iran

- together/ibhlool7/main.kt
> join ibhlool7

- README.md
Adding myself to the list of supporters.
> Support from NL

- README.md
- together/hello-ajayrawat/index.js
> Adding my support

- README.md
- together/khashayarghamati/main.cpp
> Add Support From Iran

- together/hamidosouli/main.js
Added my support for Javascript :)
> added main.js

- README.md
https://github.com/1995parham/github-do-not-ban-us/pull/735
> Added name to supporters!

- README.md
- together/bitianist/main.py
> Add support from an unlucky one who was born in Iran

- README-CN.md
This translation synced with commit 136dfd4220188429f4b693c16231117f0bfea93d,
adjust expressions and fix typos.
GitHub is for everyone.
GitHub 是全人类的。
> Update Chinese translation

- README.md
> It's support from me.

- README.md
I added my name to the README file for the support 💪🏻
> Add a name to README.md

- README.md
> aliwesome is supporting

- README.md
- together/DarrienG/main.kt
> Add support

- together/MehdiSoltani/index.php
Many thanks for your efforts about managing this repository. 
BR
> Add MehdiSoltani directory

- README.md
> Added supporter

- README-AR.md
Please don't use Google Translator , because there are some wrong translations ...
>  AR : Fix all bugs in README-AR.md ✔️ & add some translations 🀄️..

- together/amiteshore/main.cpp
> Support from India 🇮🇳

- together/Mustapha Limam/message.js
> Huge support from Tunisia 🇹🇳

- README-PT-BR.md
- README.md
- together/luxedo/luxedo.rock
I fixed the PT-BR links and added my support
> PT-BR links

- together/for-my-iranian-friends.sh
Fight for your place in the international and open source community.
> This is for my iranian friends and other blocked friends all around the world

- README.md
- together/DOBRO/together.erl
> Support from DOBRO

- together/cjzz
> Github is maintained by humanity

- README.md
- together/coderkoala/StopThisMadness.cpp
> ༼ つ ◕_◕ ༽つ

- README.md
- together/Dschee/GitHubIsForEveryone.playground/Contents.swift
- together/Dschee/GitHubIsForEveryone.playground/contents.xcplayground
Here's my little supporting PR. Good luck! 🇮🇷
> Add project support from Dschee using Swift

- README.md
> Added Saulo Nunes as a Supporter

- README.md
sorry @1995parham  :sob:
I forgot to add to README.md
> Add Korean to README.md

- README.md
- together/alencarlucas/brazil.js
> Add support from Brazil 🇧🇷

- README.md
supporter from China
Update README.md
> supporter from China

- README.md
The last I can do, Thanks for this project :+1:
> add @TomasVotruba supporter

- README.md
- together/blogwy/app.js
> add issues-1060

- README.md
- together/jaffog/message.php
Best of luck in your quest to freedom!
> Adds my message.

- together/ungerfall/main.cs
> Add support from ungerfall

- together/Minabsapi/GitHub_is_for_everyone.java
Love and encouragements to our Iranian colleagues.
> GitHub is for everyone.

- README.md
- together/jjavierdguezas/github_for_everyone.py
As a Cuban, I have been under the shit of US policy almost all my life, so I demand that GitHub is for everyone.
> github is for everyone!

- together/di3goCS/support.c
> Support message

- together/zhangzongbo/Support.java
Keep technology away from politics
> Keep technology away from politics

- README-KO.md
> Fix typo in README-KO.md

- README.md
- together/micheleriva/main.hs
> Added my support script

- README-JA.md
- README.md
> Japanese (日本語) translation

- README.md
- together/Unrooted/main.scala
Support from me. Github is for everyone.
> Support from Unrooted #GitHubIsForEveryone

- together/Webbiii/index.php
> Its now in php

- README.md
- together/berkandirim/index.js
> added berkandirim

- README.md
- together/mathieutu/index.ts
Open source rules are simple:
1. Free Redistribution
2. Source Code
3. Derived Works
4. Integrity of The Author's Source Code
5. **No Discrimination Against Persons or Groups**
6. No Discrimination Against Fields of Endeavor
7. Distribution of License
8. License Must Not Be Specific to a Product
9. License Must Not Restrict Other Software
10. License Must Be Technology-Neutral
> Support from France  🇫🇷

- README.md
- together/LucasHaddad/githubForEveryone.sh
> githubForEveryone

- README.md
> Support from Brazil

- README.md
- together/netapau/githubIsForEveryone.go
- together/netapau/main.go
- together/netapau/main_test.go
> GitHub power abuses

- README.md
- together/kssioalmeida/index.js
> Add support kssioalmeida from Brazil

- together/lordmulder/GitHub_is_for_everyone.cpp
OpenSource belongs to everyone !!!
> Support from Germany

- README.md
I updated the `Further Readings` section to include changes suggested by #1180.
> Update README.md's media coverage

- supporters.json
> The first open source for me

- README.md
> Added Me. I support

- together/blackchen/gitHubisForEveryone.sh
> Blackchen githubforeveryone

- together/arnojin.cs
> Support from China !

- README.md
In episode 368 of the Coder Radio podcast, they talked about the GitHub issue.
> Add coder radio talk about the problem to the readme

- README-CN.md
- README-TW.md
I hope this was just a mistake. Please, no politics in this repo at least.
> Add missing CN & TW link to each other

- together/JeanMatias/supports.py
> supports.py

- together/fengzikaisa/main.js
> from China`s coder

- together/extending/index.html
- together/extending/main.js
> support for everyone

- together/LiamKenneth/Together.cs
Fixes a simple typo `(`.
Github is for everyone!
> Fix Together.cs

- together/llaravell/llaravell.js
- together/llaravell/llaravell.php
- together/llaravell/llaravell.py
this is a contribute from me @llaravell
> Adding llaravell folder to together

- together/s010s/github-do-not-ban-us.js
support this project and leave github a message that we are together and we are freedom.
> add new together & supporter

- together/sathish.js
> Created sathish.js

- README.md
- together/saurabhdaware/support.js
> Support from india

- README.md
- together/turboMaCk/Main.hs
> adding myself as a supporter

- supporters.json
- together/asarthas/main.m
Add supporters.json.
Entries extracted using a regex-based flow so there may be potential mistakes. 
Unknown values are filled with `?`. We need to somehow fill them.
Order is preserved as-is (first PR first)
> feat: add supporters.json

- README.md
- together/Danct12/github-is-for-everyone.sh
GitHub should be for everyone, at all ages, all around the world.
Also, Huong Tram is my favorite singer.
> [info] message to github

- README.md
Already alphabetically ordered.
> Growing the list of brazilian supporters.

- supporters.json
- together/Carey6918/main.go
Change-Id: I596ffa465e015b8f68496f9feee838f2454213f4
> support from China 🇨🇳

- README.md
- together/zawzaww/main.cpp
> GitHub is for everyone: Add support from Myanmar

- supporters.json
> Support from Egypt

- README.md
- together/webstyle/index.ts
> Added a supporter from Uzbekistan

- together/donggang/SupportFromCn
> Support From Cn

- README-ES.md
> README-ES.md updated.

- README.md
- together/smokehill/main.py
> support from Crimea

- together/Drichao/Protect.ts
Do not let the poison of politic affects open source, shame on US goverment.
> Here is Philippines, I support Iran friends.

- supporters.json
- together/Garamda.py
Hereby I send a pull request, as a support for all Github users.
If there is something wrong with my pull request, please let me know.
Best regards,
Garam
> Support for blocked Github users

- together/mishaor/main.js
This is just wrong. Banning other people based on their nationality is flawed on so many levels.
> Voiced my support.

- supporters.json
Added my name in the supporters.json
> Update supporter list

- README.md
Isn't there a way to propagate users from supporters.json to all readme files via script?
> add myself on supporters list in Readme.md

- README-ES.md
The current message had a lot of typos, bad translations and was outdated.
I tried to make it up-to-date and easier to understand by adding all the links that were missing, as well as fixing the typos and replacing some words with others that fit better.
I know this isn't really helpful and that you guys are still being affected by the crappy US sanctions, but at least I can give my little support to help you.
Remember Spain supports you guys!
> Properly translated message

- README.md
Add myself to list of supporters
> Support from Nigeria

- README-ES.md
- README-KO.md
> Fix anchor
